name: Big Bang CI/CD Pipeline
run-name: "üõ†Ô∏è ${{ github.event.head_commit.message }} (${{ github.sha }})"
on:
  push: 
    branches:
      - big-bang-demo   #normally 'main'

jobs:
  ci-frontend:
    uses: ./.github/workflows/ci-frontend.yml
    with:
      ref: ${{ github.sha }}    

  ci-backend:
    uses: ./.github/workflows/ci-backend.yml
    with:
      ref: ${{ github.sha }}    

  cd-backend:
    needs: [ci-frontend, ci-backend]
    uses: ./.github/workflows/cd-backend.yml
    with:
      ref: ${{ github.sha }}
      backend_host: ec2-98-81-131-31.compute-1.amazonaws.com
    secrets: inherit

  cd-frontend:
    needs: [ci-frontend, ci-backend]
    uses: ./.github/workflows/cd-frontend.yml
    with: 
      ref: ${{ github.sha }}  
      bucket_name: anyhasher-big-bang
      frontend_host: anyhasher-big-bang.s3-website-us-east-1.amazonaws.com
      backend_host: ec2-98-81-131-31.compute-1.amazonaws.com
    secrets: inherit