name: CI/CD Pipeline

on: 
  push: 
    branches:
      - olt

jobs:
  build: 
    name: Build Frontend Artifact
    needs: audit
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 16
        uses: action/setup-node@v3
        with: 
          node-version: 16.x
      
      - name: Install deps
        run: |
          cd frontend 
          npm i
      
      - name: Build code
        run: cd frontend && npm run build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with: 
          path: frontend/build
  
  audit:
    name: ğŸ›¡ï¸ Audit Frontend Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for vulnerabilities
        run: cd frontend && npm audit --omit=dev
