name: CI/CD Pipeline
run-name: "ğŸ› ï¸ ${{ github.event.head_commit.message }} (${{ github.sha }})"

on: 
  push:
    branches:
      - olt

jobs:
  build: 
    name: ğŸ› ï¸ Build Frontend Artifact
    needs: 
      - audit
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: Setup Note 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
    
      - name: Install deps
        run: cd frontend && npm i
      
      - name: Compile code
        run: cd frontend && npm run build
    
  audit: 
    name: ğŸ›¡ï¸ Audit Frontend Packages
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      
      - name: Check for vulnerabilities
        run: cd frontend && npm audit --production --audit-level=medium



    