name: CI/CD Pipeline

on:
  push:
    branches:
      - olt

jobs:
  build: 
    name: Build Frontend Artifact
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v3

      - name: ensure node installed and right version
        uses: actions/setup-node@v3
        with: 
          node-version: 16.x

      - name: install deps
        run: cd frontend && npm i

      - name: compile/build
        run: cd frontend && npm run build

      - name: upload the artifact
        uses: actions/upload-pages-artifact@v1
        with: 
          path: frontend/build
  
  security-audit: 
    name: Check for vulnerabilities in my deps
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: ensure node installed and right version
        uses: actions/setup-node@v3
        with: 
          node-version: 16.x

      - name: audit
        run: cd frontend && npm audit --omit=dev